resources:
  - ../../base
  - pvc.yaml

images:
  - name: dummy
    newName: harbor-uqi.boer.id/ci-cd/flask-crud
    newTag: 12-dev

patches:
  - path: patch/deployment-patch-pvc.yaml
  - path: patch/replicas.yaml
