resources:
  - ../../base
  - pvc.yaml

images:
  - name: dummy
    newName: harbor-uqi.boer.id/ci-cd/flask-crud
    newTag: 1-prod

patchesStrategicMerge:
  - patch/deployment-patch-pvc.yaml

configMapGenerator:
- name: todo-app-config
  envs:
  - config/config.env

secretGenerator:
- name: todo-app-secret
  envs:
  - secret/secret.env
