apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-flask
spec:
  template:
    spec:
      containers:
      - name: crud-flask
        volumeMounts:
        - name: db-storage
          mountPath: /data
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: crud-flask-pvc
