apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-db
  template:
    metadata:
      labels:
        app: todo-app-db
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
