apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  template:
    spec:
      containers:
      - name: todo-app
        envFrom:
        - configMapRef:
            name: todo-app-config
        - secretRef:
            name: todo-app-secret
